image: registry.gitlab.com/greenfox/godot-build-automation:3.4

#todo add version script


stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
  - ./gitCommitLog.sh
  - builder
  artifacts:
    paths:
    - public/*
  only:
  - master


pages:
  stage: test
  image: alpine
  dependencies:
    - build
  script:
  - echo "deploying to pages"
  artifacts:
    paths:
    - public/*
  only:
  - master

# SET $BUTLER_API_KEY
itch:
  stage: publish
  variables:
    itchTarget: "greenf0x/godot-html5-webcam"
  script:
  - wget -q -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
  - unzip butler.zip
  - chmod +x butler
  - mv public/HTML5/*.html public/HTML5/index.html && ./butler push public/HTML5 ${itchTarget}:HTML5
  when: manual
  dependencies:
    - build
  only:
  - master
